export const sectionOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Get Help',
  headline: 'Post help requests and receive help of all kinds.',
  description:
    'Using Superfluid, our helpseeker can pay for the request adverts using a continious cash-flow. Allowing them to pay for the time of service and not a second more! ',
  buttonLabel: 'Get Started',
  imgStart: false,
  alt: 'getHelp',
  dark: true,
  primary: true,
  darkText: false,
  lottie: require('../../lotties/getHelp.json'),
};

export const sectionTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Give Help',
  headline:
    'Become a Volunteer and help out those in need. Collect Tokens and Earn Money ',
  description: 'Find help-seekers. Offer your help and receive rewards.',
  buttonLabel: 'Learn More',
  imgStart: true,
  alt: 'giveHelp',
  dark: false,
  primary: false,
  darkText: true,
  lottie: require('../../lotties/giveHelp.json'),
  small: true,
};

export const sectionThree = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Earn Tokens',
  headline: 'Finish help requests and receive Wolon Tokens',
  description:
    'More tokens give you more voting power and more money received.',
  buttonLabel: 'Learn More',
  imgStart: false,
  alt: 'earn',
  dark: true,
  dark2: true,
  primary: true,
  darkText: true,
  lottie: require('../../lotties/crypto.json'),
  lottieWidth: 400,
  noButton: true,
  small: true,
};

export const sectionFour = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Vote',
  headline: 'Volunteers can vote on how the money should be distributed.',
  description:
    'Volunteers with Wolon tokens can decide on what percentage of the money should be distributed among themselves and what percentage to give to charity',
  buttonLabel: 'Learn More',
  imgStart: true,
  alt: 'vote',
  dark: false,
  primary: true,
  darkText: true,
  lottie: require('../../lotties/vote.json'),
  lottieWidth: 400,
  noButton: true,
  small: true,
};

export const sectionFive = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Join our Team',
  headline: 'Creating an account is easy',
  description: 'Get everything set up and ready in 3 simple steps!',
  imgStart: true,
  img: require('../../images/papers.png'),
  alt: 'Papers',
  dark: false,
  primary: false,
  darkText: true,
  steps: true,
  noButton: true,
};
